server.port = 8080

spring.application.name=michelinAPI

# MariaDB 설정
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console 

spring.jpa.hibernate.ddl-auto=none
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.url=jdbc:mariadb://13.124.127.43:3306/michelin
spring.datasource.username=root
spring.datasource.password=1234

# thymeleaf 참조 경로
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.enabled=true
spring.thymeleaf.suffix=.html
spring.thymeleaf.encoding=UTF-8

# thymeleaf에 대한 캐시를 남기지 않는다. cache=false 설정(운영시는 true)
spring.thymeleaf.cache=false

# templates 디렉토리에 파일이 있는지 없는지 체크, 없으면 에러를 발생시킨다.
spring.thymeleaf.check-template-location=true
