name: mlist build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    
    steps:
    - name: 브랜치 이동
      uses: actions/checkout@v3
      with: 
        ref: main
        
    - name: JDK 17 설치
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        Distribution: 'corretto'
        
    - name: gradlew에 실행 권한 부여
      run: chmod +x ./gradlew.bat
      shell: bash
      
    - name: Build with Gradle
      run: ./gradlew.bat build
      shell: bash
      
        
