name: mlist build

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AWS_REGION: ap-northeast-2
  AWS_S3_BUCKET: mlists3
  AWS_CODE_DEPLOY_APPLICATION: michelin-list-dev
  AWS_CODE_DEPLOY_GROUP: mlist-dev-group

jobs:
  build:
    name: build
    runs-on: windows-latest
    
    steps:
    - name: 브랜치 이동
      uses: actions/checkout@v3
      with: 
        ref: main
        
    - name: JDK 17 설치
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        Distribution: 'corretto'

    - name: Install zip
      run: choco install zip
    
    - name: gradlew에 실행 권한 부여
      run: chmod +x ./gradlew
      shell: bash

    - name: cache 비우기
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Make zip file
      run: zip -r ./${{ github.sha }}.zip .
      shell: bash
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.DEV_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.DEV_SECRET_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Upload to S3
      run: aws s3 cp --region ${{ env.AWS_REGION }} ./${{ github.sha }}.zip s3://${{ env.AWS_S3_BUCKET }}/${{ github.sha }}.zip  
        
